### ISSUE TITLE
App bar title is no longer vertically-centered

### ISSUE THREAD

**Issue by Supuhstar** [BenLeggiero/Resume#61]
![Screenshot_20200520-101522_Chrome](https://user-images.githubusercontent.com/1350020/82470723-eebcd480-9a82-11ea-8e06-68caf6bc48d3.jpg)

**Comment by BenLeggiero** [comment]
The fix is likely to be in [the stylesheets repo](https://GitHub.com/BlueHuskyStudios/stylesheets)
