### ISSUE TITLE
Change `CSS 4` to `CSS 2020`

### ISSUE THREAD

**Issue by BenLeggiero** [BenLeggiero/Resume#72]
CSS4 was never a thing and you know it. Might as well use the real name, which is easier to communicate anyhow.

https://www.w3.org/TR/css-2020/

**Comment by BobinMathew** [comment]
hi @BenLeggiero where do you want the change (file name?)

**Comment by BenLeggiero** [comment]
@BobinMathew Hi! This would go in `index.html`, `resume-basic.json`, `Leggiero-Resume_2021-01-25.txt`, and `Leggiero-Resume_2021-01-25.pdf`. If you can't adjust the PDF using the Sketch file, that's okay; I'll make a separate issue for that.

For such a simple change, dates wouldn't have to be amended, either.

Let me know if you have any more questions!

**Comment by BobinMathew** [comment]
`resume-basic.json` has css 3 not css 4 , do you want me to change that too?

**Comment by BenLeggiero** [comment]
@BobinMathew oh yes thank you!
